version: '3.8'

services:
  # 1. hello-world container
  hello-world:
    image: hello-world
    restart: on-failure

  # 2. PostgreSQL with preloaded data
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Second constainer, Sprint boot app
  sashabrava-demo-docker:
    ports:
        - "8080:8080"
    image: sashabrava/sashabrava-demo-docker:latest
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure