apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/kubernetes-default: "true"
    io.kompose.service: hello-world
  name: hello-world
spec:
  containers:
    - image: hello-world
      name: hello-world
      resources: {}
  restartPolicy: OnFailure
status: {}
