name: YAML Lint

on:
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .